import 'intro_exceptions.dart';

void main(List<String> arguments) 
{
	testTryCatch();
}


